server:
  port: 8081

spring:
  application:
    name: UnifiedLoginVerificationSystem
  mvc:
    static-path-pattern: /static/**
  # mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.9.44.141:3306/db_auth?serverTimezone=UTC
    username: root
    password: 2020151003
    # 配置Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  # ldap setting
  ldap:
    urls: ldap://139.9.44.141:389
    base: dc=yatnam,dc=com
    username: cn=admin,dc=yatnam,dc=com
    password: 123456

mybatis-plus:
  configuration:
    # 实现数据库下划线字段与实体中的驼峰属性映射
    map-underscore-to-camel-case: true
    # 开启控制台 SQL 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 生产环境，不想打印 SQL 日志，可以通过下面的配置关闭
    # log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      # NONE: 不设置id生成策略，MP不自动生成，约等于INPUT,所以这两种方式都需要用户手动设置，但是手动设置第一个问题是容易出现相同的ID造成主键冲突，为了保证主键不冲突就需要做很多判定，实现起来比较复杂
      # AUTO:数据库ID自增,这种策略适合在数据库服务器只有1台的情况下使用,不可作为分布式ID使用
      # ASSIGN_UUID:可以在分布式的情况下使用，而且能够保证唯一，但是生成的主键是32位的字符串，长度过长占用空间而且还不能排序，查询性能也慢
      # ASSIGN_ID:可以在分布式的情况下使用，生成的是Long类型的数字，可以排序性能也高，但是生成的策略和服务器时间有关，如果修改了系统时间就有可能导致出现重复主键
      id-type: auto
